# Generated by Django 4.0.3 on 2022-03-01 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='available',
        ),
    ]
